//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCInstaller.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Assets/Packages/Pearson.PSC_1.4.3_u66eud/")]
        public string PackageRelativePath {
            get {
                return ((string)(this["PackageRelativePath"]));
            }
            set {
                this["PackageRelativePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pearson.PSC_1.4.3.0.appxbundle")]
        public string AppBundleName {
            get {
                return ((string)(this["AppBundleName"]));
            }
            set {
                this["AppBundleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Dependencies/x64/Microsoft.VCLibs.x64.120.00.appx</string>
  <string>Dependencies/x86/Microsoft.VCLibs.x86.120.00.appx</string>
  <string>Dependencies/ARM/Microsoft.VCLibs.ARM.120.00.appx</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DependencyPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DependencyPaths"]));
            }
            set {
                this["DependencyPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pearson.PSC_1.4.3.0_x86__2dnf9zyx96z42")]
        public string FullPackageName {
            get {
                return ((string)(this["FullPackageName"]));
            }
            set {
                this["FullPackageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2dnf9zyx96z42")]
        public string PublisherId {
            get {
                return ((string)(this["PublisherId"]));
            }
            set {
                this["PublisherId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pearson.PSC")]
        public string PackageName {
            get {
                return ((string)(this["PackageName"]));
            }
            set {
                this["PackageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\Pearson\PSC\8-12win.zip</string>
  <string>Conent/8-12win2.zip</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ContentFilePaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ContentFilePaths"]));
            }
            set {
                this["ContentFilePaths"] = value;
            }
        }
    }
}
